spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umcdb3?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
